### PR TITLE
Add some features to v1.2

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Add some features:
* Add pattern for admin rfid card, ensuring for misleading with other characters not included on hexadecimal ones
* Ensure object_facade is created before do an attendance, else it should raise and error on display
* Improve Logger, not logger handler was setting up correctly, now log are stored in ```/var/log/ras.log``` (thanks to @etobella)
* Check Odoo, wifi and has connection to Odoo checks to debugger warns if something is wrong

CC @Eficent 

Please review @lubusax @etobella

### CODE REVIEW

**Review by lubusax — COMMENTED** [review]
ISO 14443-3A defines 3 types of UID: single ( 4 byte ), double ( 7 bytes ) and triple ( 10 bytes ). If you use other cards than the ones we deliver you with, you could find 7 or 10 bytes UIDs.

pattern="^([A-Fa-f0-9]{1,16} ....
should be 
pattern="^([A-Fa-f0-9]{1,20} ....

10bytes are 10 x 2=20 Hexadecimal Symbols

**Review by lubusax — APPROVED** [review]
what happens then... how is object_facade then created?

**Comment by etobella** [comment]
Maybe, you can add iot_call.

**Review by lubusax — APPROVED** [review]
I am learning through this...

**Review by lubusax — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@etobella it is fine, as it does not break anything, otherwise I would prefer to keep iot_call changes in a future release, with other improvements..

Could you squash commits related to iot_call, I will create an specific branch here to work in.

**Comment by HviorForgeFlow** [comment]
@lubusax you are right, let me fix it. :smile:

**Review by etobella — APPROVED** [review]

**Review by lubusax — APPROVED** [review]

**Review by lubusax — APPROVED** [review]

**Comment by etobella** [comment]
I added a try except block on our version in order to check if any error was raised and not detected. Maybe it is interesting to add it.

**Pull request merged**
