### PR TITLE
center Odoo OK message

### PR DESCRIPTION
**Pull request by lubusax**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
A more efficient way to center messages is to use this syntax:
```python
SCREEN_WIDTH = 80
msg = "Odoo OK"
msg.center(SCREEN_WIDTH)
```
`SCREEN_WIDTH` could be a property of the hardware display and this syntax will be more extensible thinking in adding translations to the strings.

cc @hveficent

**Comment by lubusax** [comment]
Not all the characters occupy the same width with the font we use.
In order to center the messages, one should be able to know how many pixels are occcupied with text and fill the rest with spaces (right and left of the message) until 128 pixels in total.

**Comment by lubusax** [comment]
> A more efficient way to center messages is to use this syntax:
> 
> ```python
> SCREEN_WIDTH = 80
> msg = "Odoo OK"
> msg.center(SCREEN_WIDTH)
> ```
> 
> `SCREEN_WIDTH` could be a property of the hardware display and this syntax will be more extensible thinking in adding translations to the strings.
> 
> cc @hveficent
Not all the characters occupy the same width with the font we use.
In order to center the messages, one should be able to know how many pixels are occcupied with text and fill the rest with spaces (right and left of the message) until 128 pixels in total.

**Comment by LoisRForgeFlow** [comment]
@lubusax Yes, that's true, then maybe is worth to make a little method that handles that automatically, similar to the built-in center method, so you can call it anytime you want to display a message centered in the screen.

**Comment by HviorForgeFlow** [comment]
@lreficent we will take into account for future updates. Thanks for reviewing

**Pull request merged**
